feat(01-building-blocks): change from failed to successful step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -13,7 +13,9 @@ jobs:
     steps:
       - name: Failed step
         run: |
-            echo "This step will fail"
-            exit 1
+            # echo "This step will fail"
+            # exit 1
+            echo "I will succeed"
+            exit 0
       - name: Say Goodbye
         run: echo "Goodbye!"
