feat(01-building-blocks): add workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,19 +1,19 @@
 name: 01 - Building Blocks
 
-on: workflow_dispatch
+on: push
 
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-      - name: Say hello
-        run: echo "Hello, world!" 
+      - name: Say Hello
+        run: echo "Hello, World!"
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Successful step
+      - name: Failed step
         run: |
-          echo "I will succeed"
-          exit 0
-      - name: Say goodbye
-        run: echo "Goodbye, world!"
+            echo "This step will fail"
+            exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye!"
